spring:
  application:
    name: orders

  datasource:
    url: jdbc:postgresql://localhost:5432/orders-db
    password: admin123
    username: admin
    driver-class-name: org.postgresql.Driver

  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update

  output:
      ansi:
        enabled: ALWAYS

  kafka:
    bootstrap-servers: http://localhost:29092
    consumer:
      group-id: ecommerce-updated-order
      auto-offset-reset: earliest

server:
    port: 8083

logging:
   pattern:
     console: "%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n"

service-orders:
  orders:
    clients:
      products:
        url: 'http://localhost:8081/api/products'
      customers:
        url: 'http://localhost:8082/api/customers'

  config:
    kafka:
      server-url: 'http://localhost:29092'
      topics:
        orders-paid: 'ecommerce.orders-paid'
        orders-shipped: 'ecommerce.orders-shipped'
        orders-invoiced: 'ecommerce.orders-invoiced'
