version: '3.9'

networks:
  database-network:
    driver: bridge

services:
  postgres:
    restart: always
    image: postgres:16
    container_name: db_services
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_MULTIPLE_DATABASES: product-service, order-service, customer-service
    ports:
      - "5432:5432"
    networks:
      - database-network
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_admin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - database-network