spring:
  application:
    name: invoicing

  kafka:
    bootstrap-servers: http://localhost:29092
    consumer:
      group-id: ecommerce-invoicing
      auto-offset-reset: earliest

ecommerce:
  config:
    kafka:
      topics:
        orders-paid: ecommerce.orders-paid
        orders-invoiced: ecommerce.orders-invoiced

server:
  port: 8084

minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: admin123
  bucket-name: ecommerce-invoicing

  output:
    ansi:
      enabled: ALWAYS

  logging:
    pattern:
      console: "%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n"
