spring:
  application:
    name: customers

  datasource:
    url: jdbc:postgresql://localhost:5432/customers-db
    password: admin123
    username: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8082

service-customer:
  customer:
    clients:
      orders:
        url: 'http://localhost:8083/api/orders'


  output:
    ansi:
      enabled: ALWAYS

  logging:
    pattern:
      console: "%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n"
