spring:
  application:
    name: Logistic

  kafka:
    bootstrap-servers: http://localhost:29092
    consumer:
      group-id: ecommerce-logistic
      auto-offset-reset: earliest

ecommerce:
  config:
    kafka:
      topics:
        orders-invoiced: ecommerce.orders-paid
        orders-shipped: ecommerce.orders-shipped

server:
  port: 8084